language: php

dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2

install:
  - composer install --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress

matrix:
  fast_finish: true

  allow_failures:
    - php: 7.2

  include:
    - php: 7.0

    - php: 7.0

    - php: 7.1

notifications:
  email: false


script:
  - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then export CODECOVERAGE=1; vendor/bin/phpunit --coverage-clover=clover.xml; fi

after_success:
  - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then bash <(curl -s https://codecov.io/bash); fi
